version: "3.9"
services:
  mysql-router:
    image: mysql/mysql-router:8.0
    container_name: mysql-router
    environment:
      - MYSQL_HOST=mysql-primary
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    depends_on:
      - mysql-primary
      - mysql-replica1
      - mysql-replica2
  mysql-primary:
    image: mysql/mysql-server:8.0
    container_name: mysql-primary
    ports:
      - '9301:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=testdb
    volumes:
      - ./data/mysql-primary:/var/lib/mysql
      - ./conf/mysql-primary/primary.cnf:/etc/my.cnf
    command: bash -c "chmod 644 /etc/my.cnf && /entrypoint.sh mysqld"
  mysql-replica1:
    image: mysql/mysql-server:8.0
    container_name: mysql-replica1
    ports:
      - '9302:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=testdb
    volumes:
      - ./data/mysql-replica1:/var/lib/mysql
      - ./conf/mysql-replica1/replica1.cnf:/etc/my.cnf
    command: bash -c "chmod 644 /etc/my.cnf && /entrypoint.sh mysqld"
    depends_on:
      - mysql-primary
  mysql-replica2:
    image: mysql/mysql-server:8.0
    container_name: mysql-replica2
    ports:
      - '9303:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=testdb
    volumes:
      - ./data/mysql-replica2:/var/lib/mysql
      - ./conf/mysql-replica2/replica2.cnf:/etc/my.cnf
    command: bash -c "chmod 644 /etc/my.cnf && /entrypoint.sh mysqld"
    depends_on:
      - mysql-primary
