spring:
  datasource:
    driver-class-name: org.h2.Driver
    # url: jdbc:h2:mem:test
    url: jdbc:h2:./data/test
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  sql:
    init:
      schema-locations: classpath:scripts/schema-h2.sql
      data-locations: classpath:scripts/data-h2.sql
      username: root
      password: 123456
      mode: always
  h2:
    console:
      enabled: true
